version: "3.7"

services:
  api:
    build: ./backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    ports:
      - 8080:8080
    depends_on:
      - db
      - nginx
    networks:
      - network-backend
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    volumes:
      - server_db:/var/lib/mysql
    networks:
      - network-backend
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/key.pem:/etc/nginx/certs/key.pem
      - ./nginx/cert.pem:/etc/nginx/certs/cert.pem
    networks:
      - network-backend
    ports:
      - 80:80

volumes:
  server_db:

networks:
  network-backend: